
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: my_sqlserver
    environment:
      SA_PASSWORD: "veryverystrong@Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data: